name: dopa_mine
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  fluid_bottom_nav_bar: ^1.4.0
  google_fonts: ^4.0.3
  flutter_datetime_picker: ^1.5.1
  flutter_countdown_timer: ^4.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

